name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main   # or your branch
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Nuxt app
        run: npm run build

      - name: Prepare mock-data inside server folder
        run: |
          mkdir -p .output/server/public/mock-data
          cp -r .output/public/mock-data/* .output/server/public/mock-data/

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}          
          action: "upload"
          app_location: "/"                             # Location of your frontend source code
          api_location: ".output/server"               # Location of your API (Nitro server/build)
          output_location: ".output/public"            # Location of your generated static site files
